name: release client executable

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build-win:
    name: build windows
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: set up go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22.5
          check-latest: true
          cache: true
          cache-dependency-path: client/go.mod

      - name: build client
        run: cd client && go build -o client-${{ github.event.release.tag_name }}.exe

      - name: upload artifact
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: client/client-${{ github.event.release.tag_name }}.exe
